### PR TITLE
Suggestion for a small wording change

### PR DESCRIPTION
**Pull request by relsqui**
"as much as you can" -> "as much as you want"

because heck, there'll be more fossils to collect tomorrow either way :)

### CODE REVIEW

**Comment by wavebeem** [comment]
How about "Complete daily tasks." shorter and to the point. :)

**Comment by relsqui** [comment]
that works! done, hastily enough to have a typo in the commit message, sorry about that 😅 I'll let you choose how much you care to tidy it up heh

**Comment by wavebeem** [comment]
thanks!

**Comment by relsqui** [comment]
likewise, and thanks for making the thing! you've spared me from the delusion that I was ever going to get around it, haha (and you did a better job)

**Comment by wavebeem** [comment]
yeah, i love being the first person to snatch the low hanging fruit of "small utility site but with decent UX" like <https://pkmn.help>.

**Pull request merged**
